# Generated by Django 5.2.10 on 2026-01-26 13:21

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OrderStatus",
            fields=[
                ("statusID", models.AutoField(primary_key=True, serialize=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Processing", "Processing"),
                            ("Holding", "Holding"),
                            ("Shipping", "Shipping"),
                            ("Completed", "Completed"),
                            ("Cancelled", "Cancelled"),
                        ],
                        default="Processing",
                        max_length=20,
                    ),
                ),
                ("updatedDate", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "order_status",
            },
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                ("customerID", models.AutoField(primary_key=True, serialize=False)),
                ("firstName", models.CharField(max_length=100)),
                ("lastName", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("password", models.CharField(max_length=255)),
                ("phoneNumber", models.CharField(blank=True, max_length=20)),
                ("shippingAddress", models.TextField(blank=True)),
                ("createdTime", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "customer",
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                ("orderItemID", models.AutoField(primary_key=True, serialize=False)),
                (
                    "quantity",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "paidPrice",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
            ],
            options={
                "db_table": "order_item",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                ("productID", models.AutoField(primary_key=True, serialize=False)),
                ("productName", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "stockQuantity",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                ("availability", models.BooleanField(default=True)),
                ("createdTime", models.DateTimeField(auto_now_add=True)),
                ("updatedTime", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "product",
            },
        ),
        migrations.CreateModel(
            name="Store",
            fields=[
                ("storeID", models.AutoField(primary_key=True, serialize=False)),
                ("storeName", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("createdTime", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "store",
            },
        ),
        migrations.CreateModel(
            name="Vendor",
            fields=[
                ("vendorID", models.AutoField(primary_key=True, serialize=False)),
                ("vendorName", models.CharField(max_length=150)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("password", models.CharField(max_length=255)),
                ("phoneNumber", models.CharField(blank=True, max_length=20)),
                (
                    "profileImage",
                    models.ImageField(
                        blank=True, null=True, upload_to="vendor_profiles/"
                    ),
                ),
                ("createdTime", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "vendor",
            },
        ),
        migrations.CreateModel(
            name="CancelledItem",
            fields=[
                (
                    "statusID",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="cancelled_item",
                        serialize=False,
                        to="store.orderstatus",
                    ),
                ),
                (
                    "cancelledReason",
                    models.CharField(
                        choices=[
                            ("out_of_stock", "Out of Stock"),
                            ("customer_request", "Customer Request"),
                            ("damaged_item", "Damaged Item"),
                            ("payment_failed", "Payment Failed"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
            ],
            options={
                "db_table": "cancelled_item",
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                ("orderID", models.AutoField(primary_key=True, serialize=False)),
                ("orderDate", models.DateTimeField(auto_now_add=True)),
                ("shippingAddress", models.TextField()),
                (
                    "totalAmount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "customerID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to="store.customer",
                    ),
                ),
            ],
            options={
                "db_table": "order",
            },
        ),
        migrations.AddField(
            model_name="orderstatus",
            name="orderItemID",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="statuses",
                to="store.orderitem",
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="orderID",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="store.order",
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="productID",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="store.product"
            ),
        ),
        migrations.CreateModel(
            name="ClickHistory",
            fields=[
                ("historyID", models.AutoField(primary_key=True, serialize=False)),
                ("viewedDate", models.DateTimeField(auto_now_add=True)),
                (
                    "customerID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="click_history",
                        to="store.customer",
                    ),
                ),
                (
                    "productID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="store.product"
                    ),
                ),
            ],
            options={
                "db_table": "click_history",
            },
        ),
        migrations.CreateModel(
            name="ProductMedia",
            fields=[
                ("mediaID", models.AutoField(primary_key=True, serialize=False)),
                ("mediaURL", models.ImageField(upload_to="product_images/")),
                (
                    "mediaType",
                    models.CharField(
                        choices=[("image", "Image"), ("video", "Video")],
                        default="image",
                        max_length=10,
                    ),
                ),
                ("isPrimary", models.BooleanField(default=False)),
                ("sortedOrder", models.IntegerField(default=0)),
                (
                    "productID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media",
                        to="store.product",
                    ),
                ),
            ],
            options={
                "db_table": "product_media",
                "ordering": ["sortedOrder"],
            },
        ),
        migrations.CreateModel(
            name="Promotion",
            fields=[
                ("promotionID", models.AutoField(primary_key=True, serialize=False)),
                (
                    "discountRate",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("startDate", models.DateTimeField()),
                ("endDate", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("expired", "Expired"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("createdTime", models.DateTimeField(auto_now_add=True)),
                (
                    "productID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="promotions",
                        to="store.product",
                    ),
                ),
            ],
            options={
                "db_table": "promotion",
            },
        ),
        migrations.AddField(
            model_name="product",
            name="storeID",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="store.store",
            ),
        ),
        migrations.AddField(
            model_name="store",
            name="vendorID",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="store",
                to="store.vendor",
            ),
        ),
        migrations.CreateModel(
            name="CartItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                ("addedTime", models.DateTimeField(auto_now_add=True)),
                (
                    "customerID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cart_items",
                        to="store.customer",
                    ),
                ),
                (
                    "productID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="store.product"
                    ),
                ),
            ],
            options={
                "db_table": "cart_item",
                "unique_together": {("customerID", "productID")},
            },
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                ("reviewID", models.AutoField(primary_key=True, serialize=False)),
                (
                    "rating",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ]
                    ),
                ),
                ("comment", models.TextField(blank=True)),
                ("createdDate", models.DateTimeField(auto_now_add=True)),
                (
                    "customerID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="store.customer",
                    ),
                ),
                (
                    "productID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="store.product",
                    ),
                ),
            ],
            options={
                "db_table": "review",
                "unique_together": {("customerID", "productID")},
            },
        ),
        migrations.CreateModel(
            name="WishlistItem",
            fields=[
                ("wishlistItemID", models.AutoField(primary_key=True, serialize=False)),
                ("addedDate", models.DateTimeField(auto_now_add=True)),
                (
                    "originalPrice",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "discountRate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "priceAtAddedTime",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "customerID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wishlist_items",
                        to="store.customer",
                    ),
                ),
                (
                    "productID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="store.product"
                    ),
                ),
            ],
            options={
                "db_table": "wishlist_item",
                "unique_together": {("customerID", "productID")},
            },
        ),
    ]
