# Generated by Django 5.2.10 on 2026-02-05 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RefundRequest",
            fields=[
                (
                    "refundRequestID",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("reason", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("requestDate", models.DateTimeField(auto_now_add=True)),
                ("responseDate", models.DateTimeField(blank=True, null=True)),
                ("vendorNote", models.TextField(blank=True)),
                (
                    "orderItemID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="refund_requests",
                        to="store.orderitem",
                    ),
                ),
            ],
            options={
                "db_table": "refund_request",
            },
        ),
    ]
