# Generated by Django 5.2.10 on 2026-02-25 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0002_refundrequest"),
    ]

    operations = [
        migrations.CreateModel(
            name="StoreMedia",
            fields=[
                ("storeMediaID", models.AutoField(primary_key=True, serialize=False)),
                ("image", models.ImageField(upload_to="store_photos/")),
                ("caption", models.CharField(blank=True, max_length=200)),
                ("uploadedTime", models.DateTimeField(auto_now_add=True)),
                (
                    "storeID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shop_photos",
                        to="store.store",
                    ),
                ),
            ],
            options={
                "db_table": "store_media",
                "ordering": ["uploadedTime"],
            },
        ),
    ]
