# Generated by Django 5.2.10 on 2026-03-03 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0005_remove_review_unique_together"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                ("notificationID", models.AutoField(primary_key=True, serialize=False)),
                (
                    "notificationType",
                    models.CharField(
                        choices=[
                            ("new_order", "New Order Placed"),
                            ("refund_request", "Refund Request Submitted"),
                            ("wishlist_promo", "Wishlist Item On Sale"),
                            ("order_status", "Order Status Changed"),
                            ("refund_response", "Refund Response"),
                        ],
                        max_length=30,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("message", models.TextField()),
                ("link", models.CharField(blank=True, max_length=255)),
                ("isRead", models.BooleanField(default=False)),
                ("createdTime", models.DateTimeField(auto_now_add=True)),
                (
                    "customerID",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="store.customer",
                    ),
                ),
                (
                    "vendorID",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="store.vendor",
                    ),
                ),
            ],
            options={
                "db_table": "notification",
                "ordering": ["-createdTime"],
            },
        ),
    ]
