# Generated by Django 5.2.10 on 2026-03-15 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0006_notification"),
    ]

    operations = [
        migrations.CreateModel(
            name="SearchQuery",
            fields=[
                ("searchID", models.AutoField(primary_key=True, serialize=False)),
                ("query", models.CharField(max_length=255)),
                ("resultCount", models.IntegerField(default=0)),
                ("searchedAt", models.DateTimeField(auto_now_add=True)),
                (
                    "customerID",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="search_queries",
                        to="store.customer",
                    ),
                ),
            ],
            options={
                "db_table": "search_query",
                "ordering": ["-searchedAt"],
            },
        ),
    ]
